/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_willowtreeapps_jniexample_MyNativeActivity */

#ifndef _Included_com_willowtreeapps_jniexample_MyNativeActivity
#define _Included_com_willowtreeapps_jniexample_MyNativeActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_willowtreeapps_jniexample_MyNativeActivity
 * Method:    updateWordCounter
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_willowtreeapps_jniexample_MyNativeActivity_updateWordCounter
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
